### ISSUE TITLE
Berry Bush Mod Compat

### ISSUE THREAD

**Issue by WenXin20** [daPoseidonGuy/strawgolem#3] opened 2020-06-23 06:55 UTC
`Straw Golems v1.7`

The Straw Golem won't harvest berries from other mods. The ones I tried was the Blueberry Bush from Biomes You'll Go, the Foul Berry Bush from Autumnity, and the Berry Bushes from Simple Farming.

I've also noticed that the golems break and replant the Sweet Berry Bushes, instead of just leaving the bush fully grown and only harvesting the berries, which is what can normally be done with a right-click.

**Comment by daPoseidonGuy** [comment] 2020-06-26 21:00
Sorry for missing this!

I've fixed the replanting issue - as for the compatibility thing - this surprises me, it should be working. But I'm looking at it now :)

**Comment by WenXin20** [comment] 2020-06-26 21:06
Thanks!

**Comment by daPoseidonGuy** [comment] 2020-06-26 21:19
Ok, so the original issue was just one of my checks being too specific.
As it was though, only the Biomes You'll go bush would have worked anyways, as the other one's dont extend SweetBerryBushBlock.

However, I'm testing a way now to be able to allow for a general solution for anything that extends BushBlock and is an IGrowable.

I'll keep you posted :)

**Comment by daPoseidonGuy** [comment] 2020-06-26 23:13
Hey! I have a candidate for this - try it out and see if the issue is solved (note theres a jar in the zip - use that, github doesnt allow you to upload jars directly)

[strawgolem-1.15.2-1.7.1.zip](https://github.com/daPoseidonGuy/strawgolem/files/4839569/strawgolem-1.15.2-1.7.1.zip)

**Comment by WenXin20** [comment] 2020-06-27 08:08
Thanks, I'll see if I can test it soon

**Comment by WenXin20** [comment] 2020-07-01 05:14
It works, but only partially.
For the vanilla bush, it'll only harvest one of the berries, even though the player can gather berries when the bush reaches age 2 or age 3.

For Autumnity, the Foul Berry Bush is two blocks tall, and the top half is broken when harvested.

For Biomes You'll Go, the Blue Berries seem to be voided when harvested.

For Simple Farming, instead of gathering the berries, it instead harvests the bush and dupes it.

**Comment by daPoseidonGuy** [comment] 2020-07-13 02:06
I just want to let you know that I haven't forgot about this - it just got put on the backburner while i was changing the main way golems harvest crops

Right now:
- BYG berries get picked properly but they aren't detected when they grow? or at least when i bone meal them bc they didnt seem to grow otherwise..
- Simple Farming it voids the berries now and doesnt detect when they grow
- Autumnity works except it still deletes the top half

**Comment by WenXin20** [comment] 2020-07-13 02:14
Thanks, I had the same problem with the blueberries from BYG as well.

**Comment by daPoseidonGuy** [comment] 2020-07-15 05:54
Update:
- I still dont see how blueberries are supposed to naturally grow, but they work when they are bonemealed now
- The autumnity bushes work now and the top half no longer gets deleted
- Simple farming is harder bc the bushes dont post the CropGrowEvent when they grow.. so I'm still investigating on that one

**Comment by WenXin20** [comment] 2020-07-15 06:33
The blueberries not naturally growing is probably a byg bug.

**Comment by daPoseidonGuy** [comment] 2020-07-15 22:20
Ok so for simple farming idk if I'll be able to add compatibility for their berries tbh

So first off, they dont fire CropGrownEvent when they grow naturally. So every 300 ticks the golems search themselves for a grown crop, that *will* find them. And bonemealing them will also find them.

So that issue isnt a deal breaker, but the problem is that the berry bush harvesting in that mod - they do it by listening to PlayerInteractEvent.RightClickBlock event instead of overriding the onBlockActivated event in their berry bush class

**Comment by WenXin20** [comment] 2020-07-15 22:37
Ah, that's too bad. But I don't mind if it can't be supported, it's not super important to me.

**Comment by daPoseidonGuy** [comment] 2020-07-16 21:11
Turns out making a fake player is actually much much simpler than I had imagined it would be

https://drive.google.com/file/d/1XD9fZTPkxfy2rAgOCWXqGvXLWKv-9XrP/view?usp=sharing

Try this out :)

**Comment by WenXin20** [comment] 2020-07-16 21:18
Thanks! I'll see if I can try it out tomorrow.

**Comment by WenXin20** [comment] 2020-07-17 07:04
Seems to be working great, with both the iron Chests and the Berry Bushes!
Also, is the chest supposed to play an open animation, or is it only the sound that will play?

**Comment by daPoseidonGuy** [comment] 2020-07-29 00:21
It's just a sound right now :)

I'll see what I can do about the cattail seeds and pokecube mods

**Comment by WenXin20** [comment] 2020-08-01 01:09
Another thing I've noticed, with Simple Farming two block tall crops, the golem will harvest, but the top half will drop onto the ground instead, such as with the Kenaf crop.

**Comment by daPoseidonGuy** [comment] 2020-08-19 23:28
[strawgolem-1.15.2-1.9-beta-2.zip](https://github.com/daPoseidonGuy/strawgolem/files/5099825/strawgolem-1.15.2-1.9-beta-2.zip)

Try this!

It should fix compat with the cantaloupe, squash etc.

Should also fix the floating top half with Pokecube AIO, but I'm not sure on that one since the mod doesn't seem to want to run on my installation.

**Comment by WenXin20** [comment] 2020-08-20 02:18
I'll see if I can it a try tomorrow, thanks!

**Comment by daPoseidonGuy** [comment] 2020-08-26 14:13
Moving this to here https://github.com/daPoseidonGuy/strawgolem/issues/10 and closing

**Closed by daPoseidonGuy** 2020-08-26 14:13 UTC
