### ISSUE TITLE
[1.15.2][1.9-beta-2] Server crashes when breaking a boat with a Straw Golem in it

### ISSUE THREAD

**Issue by wchen1990** [daPoseidonGuy/strawgolem#11] opened 2020-08-26 19:03 UTC
[Here's the crash report.](https://github.com/daPoseidonGuy/strawgolem/files/5131848/crash-2020-08-26_14.56.22-server.txt)

Hate to be the bearer of more bad news. But, server crashes when you try to break a boat with the little guy in it. The server can still be started up again so that's fine. Since I found this issue, I figured I'd see if it'd have the same issue with Minecarts. Turns out, you can't break Minecarts if they're in them. The boat thing I have tested locally in Singleplayer and on my server. The Minecart thing I only tested in Singleplayer.

Let me know if you need any more information.

**Comment by daPoseidonGuy** [comment] 2020-08-27 15:05
Fixed in latest commit. Which version are you playing on?

**Comment by wchen1990** [comment] 2020-08-27 15:33
Playing on Forge 1.15.2-31.2.36, and was using the latest 1.15.2 release for Straw Golems (strawgolem-1.15.2-1.9-beta-2.jar). I got the latest file from Curseforge.

**Comment by daPoseidonGuy** [comment] 2020-08-27 16:47
[strawgolem-1.15.2-1.9-beta-2.zip](https://github.com/daPoseidonGuy/strawgolem/files/5137696/strawgolem-1.15.2-1.9-beta-2.zip)

Here you go!

**Comment by wchen1990** [comment] 2020-08-27 17:40
[Seems like that version doesn't start at all.](https://github.com/daPoseidonGuy/strawgolem/files/5137887/crash-2020-08-27_13.36.23-client.txt)

Unfortunately, can't test the boat use case since I'm getting a different error now. Might be related to your previous commit? Also, no worries about the version question, thought you wanted to know what Forge version I was using, but included which strawgolem version I was using just in case too.

**Comment by daPoseidonGuy** [comment] 2020-08-27 19:56
What in the world... maybe it compiled wrong. Could be the commit before since I only tested it in IDE. I'll update soon.

**Comment by daPoseidonGuy** [comment] 2020-08-28 01:48
[strawgolem-1.15.2-1.9-beta-2.zip](https://github.com/daPoseidonGuy/strawgolem/files/5139566/strawgolem-1.15.2-1.9-beta-2.zip)

Here! Should be working now. Sorry about that!

**Comment by wchen1990** [comment] 2020-08-28 18:22
Thanks for the quick updates!

I've tested breaking them out of minecarts and boats and it all works as expected.

Here's an image with two of them on a boat:
![Two Straw Golems in a boat](https://user-images.githubusercontent.com/8822548/91602609-a17db800-e939-11ea-95c5-8e7339559800.png)

**Comment by daPoseidonGuy** [comment] 2020-08-28 22:55
They're so cute when they're almost dead (remember to give them some wheat!)

Glad to see the issue is fixed. Closing it :)

**Closed by daPoseidonGuy** 2020-08-28 22:55 UTC
